app/Http/routes.php
<?php

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

#Installation script Routes
Route::group(array('prefix'=>'install','before'=>'install'),function()
{
    Route::get('/','Backend\InstallController@index');
    Route::get('/database','Backend\InstallController@getDatabase');
    Route::post('/database','Backend\InstallController@postDatabase');
    Route::get('/user','Backend\InstallController@getUser');
    Route::post('/user','Backend\InstallController@postUser');
});

//Route::group(['middleware' => 'install'], function(){
Route::group(['middleware' => 'auth'], function(){
    Route::get('/', 'Backend\DashboardController@index');
    Route::get('home', 'Backend\DashboardController@index');
    Route::group(array('prefix'=>'backend', 'middleware' => 'auth' ),function()
    {
        Route::resource('colors', 'Backend\ColorsController');
        Route::resource('categories', 'Backend\CategoriesController');
        Route::resource('conditions', 'Backend\ConditionsController');
        Route::resource('features', 'Backend\FeaturesController');
        Route::resource('fuels', 'Backend\FuelsController');
        Route::resource('makes', 'Backend\MakesController');
        Route::resource('transmissions', 'Backend\TransmissionsController');
        Route::resource('models', 'Backend\VehicleModelsController');
        Route::resource('listings', 'Backend\ListingsController');
        Route::post('listings/getModels', 'Backend\ListingsController@getModels');
        Route::resource('images', 'Backend\ImagesController');
        Route::resource('users', 'Backend\UsersController');
        Route::resource('settings', 'Backend\SettingsController');
        # Profile
        Route::get('profile', 'Backend\UsersController@editProfile');
        Route::post('profile', 'Backend\UsersController@updateProfile');
        #listings
        Route::get('listingsFilter', 'Backend\ListingsController@filter');
        #models
        Route::get('modelsFilter', 'Backend\VehicleModelsController@filter');
    });
});
//});
Route::resource('colors', 'ColorsController');
Route::resource('categories', 'CategoriesController');
Route::resource('conditions', 'ConditionsController');
Route::resource('features', 'FeaturesController');
Route::resource('fuels', 'FuelsController');
Route::resource('makes', 'MakesController');
Route::resource('transmissions', 'TransmissionsController');
Route::resource('models', 'VehicleModelsController');
Route::resource('listings', 'ListingsController');
Route::resource('feature_listings', 'FeatureListingController');
Route::resource('vehicle_images', 'VehicleImagesController');
Route::get('settings', 'SettingsController@index');


//protected routes
Route::group(array('prefix' => 'api/v1', 'before' => 'oauth'), function () {
    Route::resource('colors', 'ColorsController');
});
//Route::resource('colors', 'ColorsController', array('only' => array('index', 'show')));


//Respond to incoming access token requests
Route::post('api/v1/oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});

app/Http/Controllers/Backend/ListingsController.php
<?php namespace App\Http\Controllers\Backend;

use App\Http\Requests\ListingRequest;
use App\Dealer\Repositories\Contracts\ListingInterface;
use App\Dealer\Repositories\Contracts\VehicleImageInterface;
use App\Dealer\Repositories\Contracts\FeatureListingInterface;
use Illuminate\Support\Facades\Request;

class ListingsController extends AdminController {


    /**
     * @var
     */
    protected $listingRepository;

    /**
     * @var
     */

    protected $listingTransformer;
    /**
     * @var
     */

    protected $listingImagesRepository;

    /**
     * @var
     */

    protected $featureListingRepository;


    public function __construct(ListingInterface $listingRepository, VehicleImageInterface $listingImageRepository, FeatureListingInterface $featureListingRepository){
        $this->listingRepository = $listingRepository;
        $this->listingImagesRepository = $listingImageRepository;
        $this->featureListingRepository = $featureListingRepository;
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
       $makes      = $this->listingRepository->makes_select();
       $load = ['images'];
       $listings = $this->listingRepository->getAll($load);
       $data =  $this->respondWithPagination($listings,[
            'listings' => $listings->all()
        ]);
       if(Request::ajax()){
           $view = view('listings.partials._listings', compact('data'))->render();
           $paginator = str_replace('/?', '?', $data['paginator']['links']);
           return \Response::json(['success'=> true, 'html' => $view, 'paginator'=>$paginator], 200);
       }
        return view('listings.index',compact('data', 'makes'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        $makes      = $this->listingRepository->makes_select();
        $colors     = $this->listingRepository->color_select();
        $conditions = $this->listingRepository->condition_select();
        $categories = $this->listingRepository->category_select();
        $transmissions = $this->listingRepository->transmission_select();
        $fuels      = $this->listingRepository->fuel_select();
        $features      = $this->listingRepository->feature_select();
		return view('listings.create', compact('makes','colors','categories','conditions','transmissions','fuels','features'));
	}

    /**
     * Store a newly created resource in storage.
     * @param ListingRequest $request
     * @return mixed
     */
    public function store(ListingRequest $request)
	{

        $listing = $this->listingRepository->create($request->all());
        if($listing){
            //Images upload
            for($imageCount = 1; $imageCount <= 5; $imageCount++){
                $image_name = 'image_'.$imageCount;
                if ($request->hasFile($image_name))
                {
                    $file = $request->file($image_name);
                    $filename = strtolower(str_random(50) . '.' . $file->getClientOriginalExtension());
                    $file->move('assets/img/vehicle', $filename);
                    \Image::make(sprintf('assets/img/vehicle/%s', $filename))->resize(150,150, function ($constraint) {
                        $constraint->aspectRatio();
                    })->save('assets/img/vehicle/thumb/'.$filename);
                    $imageData = array(
                        'listing_id'  => $listing->uuid,
                        'filename'    => $filename,
                    );
                    $this->listingImagesRepository->create($imageData);
                }
            }
            //save Features
            $features = $request->get('features') ? $request->get('features') : null;
            $listing->setFeatures($features);

            \Session::flash('success', 'Success !! Vehicle listing has been created.');
            return $this->respondWithSuccess('Success !! Vehicle listing has been created.');
        }


        return $this->respondNotSaved("Unexpected error just happened");
	}

    /**
     * Display the specified resource.
     * @param $uuid
     * @return \Illuminate\View\View|mixed
     */
    public function show($uuid)
	{
        $listing = $this->listingRepository->getById($uuid, ['featureListings']);
      //  dd($listing);

        if(!$listing)
        {
            return $this->respondNotFound('Listing not found.');
        }

        return view('listings.show', compact('listing'));
	}

    /**
     * Show the form for editing the specified resource.
     * @param $uuid
     * @return \Illuminate\View\View
     */
    public function edit($uuid)
	{
        $makes              = $this->listingRepository->makes_select();
        $colors             = $this->listingRepository->color_select();
        $conditions         = $this->listingRepository->condition_select();
        $categories         = $this->listingRepository->category_select();
        $transmissions      = $this->listingRepository->transmission_select();
        $fuels              = $this->listingRepository->fuel_select();
        $features_select     = $this->listingRepository->feature_select();
        $listing            = $this->listingRepository->getById($uuid, ['featureListings']);
        return view('listings.edit', compact('makes','colors','categories','conditions','transmissions','fuels','features_select', 'listing'));
	}

    /**
     * Update the specified resource in storage.
     * @param ListingRequest $request
     * @param $uuid
     * @return mixed
     */
    public function update(ListingRequest $request, $uuid)
	{
        if(!$request->has('active')){
            $request->merge(array('active' => 0));
        }
        if(!$request->has('featured')){
            $request->merge(array('featured' => 0));
        }


        $listing = $this->listingRepository->update($request->all(), $uuid);

        if($listing){
            //Images upload
            for($imageCount = 1; $imageCount <= 5; $imageCount++){
                $image_name = 'image_'.$imageCount;
                if ($request->hasFile($image_name))
                {
                    $file = $request->file($image_name);
                    $filename = strtolower(str_random(50) . '.' . $file->getClientOriginalExtension());
                    $file->move('assets/img/vehicle', $filename);
                    \Image::make(sprintf('assets/img/vehicle/%s', $filename))->resize(150,150, function ($constraint) {
                        $constraint->aspectRatio();
                    })->save('assets/img/vehicle/thumb/'.$filename);
                    \Image::make(sprintf('assets/img/vehicle/%s', $filename))->resize(400,400, function ($constraint) {
                        $constraint->aspectRatio();
                    })->save('assets/img/vehicle/mobile/'.$filename);
                    $imageData = array(
                        'listing_id'  => $listing->uuid,
                        'filename'    => $filename,
                    );
                    $this->listingImagesRepository->create($imageData);
                }
            }
            //save Features
            $features = $request->get('features') ? $request->get('features') : array();

            $listing->setFeatures($features);

            \Session::flash('success', 'Success !! Vehicle listing has been updated.');
            return $this->respondWithSuccess('Success !! Vehicle listing has been created.');
        }
        return $this->respondNotSaved("Unexpected error just happened");
	}

    public function getModels(){
        $make = \Request::get('make');
        $models = $this->listingRepository->models_select($make);
       return $this->respond(['models' => $models]);

    }

    public function filter(){
        $make = Request::get('make');
        $model = Request::get('model');

        $data['listings'] = $this->listingRepository->filter($make, $model);

        $view = view('listings.partials._listings_filter', compact('data'))->render();
        return \Response::json(['success'=> true, 'html' => $view], 200);
    }

    /**
     * Remove the specified resource from storage.
     * @param $uuid
     * @return mixed
     */
    public function destroy($uuid)
	{
        if($uuid == 'delete_multiple'){
            $items = json_decode($_POST['items']);
            foreach($items as $listing_id){
                $listing = $this->listingRepository->getById($listing_id);
                $listing->images()->delete();
                $listing->featureListings()->delete();
                $this->listingRepository->delete($listing_id);
            }
            \Session::flash('success', 'Success !! Vehicle listings have been deleted.');
            return \Response::json(['success'=> true, 'message' => 'Vehicle listings deleted successfully'], 200);
        }
        else{
            $listing = $this->listingRepository->getById($uuid);
            $listing->images()->delete();
            $listing->featureListings()->delete();
            if($listing->delete()){
                \Session::flash('success', 'Success !! Vehicle listing has been deleted.');
            }else{
                \Session::flash('error', 'Error !! Error deleting Vehicle listing try again.');
            }
            return redirect('backend/listings');
	    }
    }

}

app/Http/Controllers/ListingsController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\ListingRequest;
use App\Dealer\Repositories\Contracts\ListingInterface;
use App\Dealer\Transformers\ListingTransformer;
use Illuminate\Support\Facades\Request;

class ListingsController extends ApiController {


    /**
     * @var
     */
    protected $listingRepository;

    /**
     * @var
     */

    protected $listingTransformer;


    public function __construct(ListingInterface $listingRepository, ListingTransformer $listingTransformer){
        $this->listingRepository = $listingRepository;
        $this->listingTransformer = $listingTransformer;
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
        //retrieve current time of server before touching the database.
        $now = time();
        //The timestamp of the last sync call made by client
        // - if not available we assume its the first time the call is made
        //  and therefore provide no data to delete as the client has no data yet

        $modifiedSince = Request::input('modifiedSince', null);
        $syncData = $this->listingRepository->getAll();
        //Ids to desync
        $desync = null;

        if(null != $modifiedSince && is_numeric($modifiedSince)){
            //the client has timestamp
            // so return only records that have been touched since then
            $syncData = $this->listingRepository->getUpdated($modifiedSince);

            //send a list of ids to desync
            $desync = $this->listingRepository->getDeleted($modifiedSince);

        }else{
            return $this->respondWithPagination($syncData, [
                'data' => $this->listingTransformer->transformCollection($syncData->all()),
                'timestamp' => $now
            ]);
        }

        //send only the ids for the records to be deleted
        if(isset($desync)){
            $desync = $desync->fetch('uuid')->toArray();
        }

        if(null == $syncData){
            return $this->respondNotFound('No vehicle listings found');
        }

        return $this->respondWithPagination($syncData, [
            'data' => $this->listingTransformer->transformCollection($syncData->all()),
            'timestamp' => $now,
            'desync'    => $desync
        ]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

    /**
     * Store a newly created resource in storage.
     * @param ListingRequest $request
     * @return mixed
     */
    public function store(ListingRequest $request)
	{
        if($this->listingRepository->create($request->all())){
            return $this->respondWithSuccess('Success !! Vehicle listing has been created.');
        }

        return $this->respondNotSaved("Unexpected error just happened");
	}

    /**
     * Display the specified resource.
     * @param $uuid
     * @return mixed
     */
    public function show($uuid)
	{
        $listing = $this->listingRepository->getById($uuid);

        if(!$listing)
        {
            return $this->respondNotFound('Listing not found.');
        }

        return $this->respond([
            'data' => $this->listingTransformer->transform($listing)
        ]);
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

    /**
     * Update the specified resource in storage.
     * @param ListingRequest $request
     * @param $uuid
     * @return mixed
     */
    public function update(ListingRequest $request, $uuid)
	{
        if($this->listingRepository->update($request->all(), $uuid)){
            return $this->respondWithSuccess('Success !! Vehicle listing has been updated.');
        }
        return $this->respondNotSaved("Unexpected error just happened");
	}

    /**
     * Remove the specified resource from storage.
     * @param $uuid
     * @return mixed
     */
    public function destroy($uuid)
	{
        if($this->listingRepository->delete($uuid)){
            return $this->respondWithSuccess('Success !! Vehicle listing has been deleted');
        }
        return $this->respondNotFound('Vehicle listing not deleted');
	}

}

resources/views/listings/index.blade.php
@extends('layouts.main')

@section('content')
<div class="col-md-12 content-header">
    <div class="col-md-6">
        <h3><i class="fa fa-tasks pull-left"></i> @Lang('app.listings_title') </h3>
    </div>
    <div class="col-md-6">
        <h3><a class="btn btn-primary pull-right" href="{{ route('backend.listings.create') }}">@Lang('app.add_listing_btn')</a></h3>
    </div>
</div>
<section class="content">
    <div class="row">
        <div class="col-xs-12" style="padding-bottom: 10px">
            <form class="form-inline">
                <div class="form-group col-xs-3">
                    {!! Form::label('make', 'Make') !!}
                    {!! Form::select('make_id',$makes, null, ['class' => 'form-control input-sm chosen','required','id'=>'make_id']) !!}
                </div>
                <div class="form-group  col-xs-3">
                    {!! Form::label('make', ' Model') !!}
                    {!! Form::select('model_id',array(), null, ['class' => 'form-control chosen','id'=>'model_id']) !!}
                </div>
                <div class="form-group  col-xs-3" style="padding-top: 25px">
                    <button type="submit" class="btn btn-success" id="filter_listings"> <i class="fa fa-search"></i> {{ Lang::get('app.filter_listings') }}</button>
                </div>
            </form>
        </div>
   </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header"></div>
                @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
                @endif
                @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
                @endif
                <div class="box-body no-padding">
                    <table class="table table-hover table-striped" id="listings_tbl">
                        <thead>
                            <tr>
                                <th></th>
                                <th width="10%">
                                    <div class="radio">
                                        <label for="select_all"> {!! Form::checkbox('select_all','1',null,['class'=>'minimal', 'id'=>'select_all']) !!} </label> &nbsp;
                                    </div>
                                </th>
                                <th width="15%">@Lang('app.photo')</th>
                                <th width="20%">@Lang('app.details')</th>
                                <th width="10%">@Lang('app.price')</th>
                                <th width="10%">@Lang('app.created')</th>
                                <th>@Lang('app.action')</th>
                            </tr>
                        </thead>
                        <tbody id="listing_body">
                        <?php $counter = ($data['paginator']['current_page'] - 1) * $data['paginator']['limit'] + 1; ?>
                        @foreach($data['listings'] as $listing)
                        <tr>
                            <td>{{ $counter }}</td>
                            <td>
                                <div class="radio">
                                    <label for="{{$listing['uuid']}}"> {!! Form::checkbox('selected',$listing['uuid'],null,['class'=>'minimal select_record']) !!} </label> &nbsp;
                                </div>
                            </td>
                            <td><img src="{{ isset($listing['images'][0]) && $listing['images'][0]['filename'] != '' ? asset('assets/img/vehicle/thumb/'.$listing['images'][0]['filename']) : asset('assets/img/vehicle/no-image.jpg') }}" width="50%"/></td>
                            <td>
                                {!! '<strong>'.$listing['make']['make_name'].' '.$listing['model']['model_name'].'</strong> ('.$listing['registration_year'].')<br/>'  !!}
                                {!! 'Condition: '.$listing['condition']['condition_name'].'<br/>Transmission: '.$listing['transmission']['transmission_name'].'<br/>'  !!}
                                {!! 'Fuel: '.$listing['fuel']['fuel_name'] !!}
                            </td>
                            <td>{!! '<strong>'.formatMoney($listing['price']).'</strong>' !!}</td>
                            <td>{!! formatDate($listing['created_at']).'</strong>' !!}</td>
                            <td>
                                <a class="btn btn-primary btn-sm" href="{{ route('backend.listings.show', $listing['uuid']) }}"><i class="fa fa-eye"></i> @Lang('app.view')</a>
                                <a class="btn btn-success btn-sm" href="{{ route('backend.listings.edit', $listing['uuid']) }}"><i class="fa fa-pencil"></i> @Lang('app.edit')</a>
                                {!! Form::open(array("method"=>"DELETE", "route" => ['backend.listings.destroy', $listing['uuid']], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                                    <a class="btn btn-danger btn-sm btn-delete"><i class="fa fa-trash"></i>  @Lang('app.delete')</a>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        <?php $counter++; ?>
                        @endforeach
                        </tbody></table>
                        <div  id="paginationWrapper" style="text-align: center">
                            {!! str_replace('/?', '?', $data['paginator']['links']) !!}
                        </div>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
                    {!! Form::open(array("method"=>"DELETE", "route" => ['backend.listings.destroy', ''], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                    <a class="btn btn-danger btn-sm btn-delete-multiple"><i class="fa fa-trash"></i> @Lang('app.delete_multiple') </a>
                    {!! Form::close() !!}


        </div>
    </div>
</section>
@endsection
@section ('js_scripts')
@include('listings.partials._listings_js')
@endsection

resources/views/listings/show.blade.php
@extends('layouts.main')

@section('content')
<div class="col-md-12 content-header">
    <div class="col-md-6">
        <h3><i class="fa fa-tasks"></i> @Lang('app.listings_view_title') </h3>
    </div>
    <div class="col-md-6">
        <h3><a class="btn btn-primary pull-right" href="{{ route('backend.listings.index') }}">@Lang('app.back_listing_btn')</a></h3>
    </div>
</div>
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <section class="content-header">
                <h1>{{ $listing->registration_year.' '.$listing->make->make_name.' '.$listing->model->model_name }}</h1>
            </section>
            <div class="box box-primary">
                <div class="box-header"></div>
                <div class="box-body table-responsive no-padding">
                    <div class="col-xs-12">
                        <strong><p>{{ Lang::get('app.images_label') }}</p></strong>
                        @foreach ($listing['images'] as $image)
                        <div class="col-lg-2 thumb">
                            <a class="thumbnail" href="#">
                                <img src="{{ asset('assets/img/vehicle/thumb/'.$image->filename) }}" width="100%"/>
                            </a>
                        </div>
                        @endforeach
                    </div>
                    <div class="col-xs-12">
                        <p><strong>{{ Lang::get('app.vehicle_details_label') }}</strong></p>
                    </div>
                    <div class="col-xs-4">
                        <table class="table table-striped">

                            <tbody><tr>
                                <td>{{ Lang::get('app.make_label') }}</td>
                                <td>{{ $listing->make->make_name }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.model_label') }}</td>
                                <td>{{ $listing->model->model_name }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.condition_label') }}</td>
                                <td>{{ $listing->condition->condition_name }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.mileage_label') }}</td>
                                <td>{{ $listing->mileage }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.vin_number_label') }}</td>
                                <td>{{ $listing->vin_number}}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.registration_label') }}</td>
                                <td>{{ $listing->registration_year}}</td>
                            </tr>
                            </tbody></table>
                    </div>
                    <div class="col-xs-4">
                        <table class="table table-striped">

                            <tbody><tr>
                                <td>{{ Lang::get('app.price_label') }}</td>
                                <td>{{ formatMoney($listing->price) }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.exterior_color_label') }}</td>
                                <td>{{ $listing->exterior_color->color_name }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.interior_color_label') }}</td>
                                <td>{{ $listing->interior_color->color_name }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.engine_size_label') }}</td>
                                <td>{{ $listing->engine_size }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.category_label') }}</td>
                                <td>{{ $listing->category->category_name}}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.details_label') }}</td>
                                <td>{{ $listing->extra_details}}</td>
                            </tr>
                            </tbody></table>
                    </div>
                    <div class="col-xs-4">
                        <table class="table table-striped">

                            <tbody><tr>
                                <td>{{ Lang::get('app.transmission_label') }}</td>
                                <td>{{ $listing->transmission->transmission_name }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.doors_label') }}</td>
                                <td>{{ $listing->doors }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.fuel_label') }}</td>
                                <td>{{ $listing->fuel->fuel_name }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.active_label') }}</td>
                                <td>{{ $listing->active ? 'Yes' : 'No' }}</td>
                            </tr>
                            <tr>
                                <td>{{ Lang::get('app.featured_listing_label') }}</td>
                                <td>{{ $listing->featured ? 'Yes' : 'No' }}</td>
                            </tr>
                            </tbody></table>
                    </div>
                    <div class="col-xs-12">
                        <p><strong>{{ Lang::get('app.features_label') }}</strong></p>
                        @foreach($listing['featureListings'] as $feature)
                        <div class="form-group col-md-2" style="margin-bottom: 0;">
                            <div class="checkbox">
                                <div class="" style="margin-top:5px">
                                    <i class="fa fa-check"></i>
                                    {{ $feature->feature->feature_name }}

                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>


                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>




    </section>
@endsection