app/Http/routes.php
<?php

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

#Installation script Routes
Route::group(array('prefix'=>'install','before'=>'install'),function()
{
    Route::get('/','Backend\InstallController@index');
    Route::get('/database','Backend\InstallController@getDatabase');
    Route::post('/database','Backend\InstallController@postDatabase');
    Route::get('/user','Backend\InstallController@getUser');
    Route::post('/user','Backend\InstallController@postUser');
});

//Route::group(['middleware' => 'install'], function(){
Route::group(['middleware' => 'auth'], function(){
    Route::get('/', 'Backend\DashboardController@index');
    Route::get('home', 'Backend\DashboardController@index');
    Route::group(array('prefix'=>'backend', 'middleware' => 'auth' ),function()
    {
        Route::resource('colors', 'Backend\ColorsController');
        Route::resource('categories', 'Backend\CategoriesController');
        Route::resource('conditions', 'Backend\ConditionsController');
        Route::resource('features', 'Backend\FeaturesController');
        Route::resource('fuels', 'Backend\FuelsController');
        Route::resource('makes', 'Backend\MakesController');
        Route::resource('transmissions', 'Backend\TransmissionsController');
        Route::resource('models', 'Backend\VehicleModelsController');
        Route::resource('listings', 'Backend\ListingsController');
        Route::post('listings/getModels', 'Backend\ListingsController@getModels');
        Route::resource('images', 'Backend\ImagesController');
        Route::resource('users', 'Backend\UsersController');
        Route::resource('settings', 'Backend\SettingsController');
        # Profile
        Route::get('profile', 'Backend\UsersController@editProfile');
        Route::post('profile', 'Backend\UsersController@updateProfile');
        #listings
        Route::get('listingsFilter', 'Backend\ListingsController@filter');
        #models
        Route::get('modelsFilter', 'Backend\VehicleModelsController@filter');
    });
});
//});
Route::resource('colors', 'ColorsController');
Route::resource('categories', 'CategoriesController');
Route::resource('conditions', 'ConditionsController');
Route::resource('features', 'FeaturesController');
Route::resource('fuels', 'FuelsController');
Route::resource('makes', 'MakesController');
Route::resource('transmissions', 'TransmissionsController');
Route::resource('models', 'VehicleModelsController');
Route::resource('listings', 'ListingsController');
Route::resource('feature_listings', 'FeatureListingController');
Route::resource('vehicle_images', 'VehicleImagesController');
Route::get('settings', 'SettingsController@index');


//protected routes
Route::group(array('prefix' => 'api/v1', 'before' => 'oauth'), function () {
    Route::resource('colors', 'ColorsController');
});
//Route::resource('colors', 'ColorsController', array('only' => array('index', 'show')));


//Respond to incoming access token requests
Route::post('api/v1/oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});

app/Transmission.php
<?php namespace App;

class Transmission extends BaseModel {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'transmissions';

    /**
     * Main table primary key
     * @var string
     */
    protected $primaryKey = 'uuid';

    /**
     * Entities fields to be mass assigned
     * @var array
     */
    protected $fillable = array('uuid','transmission_name');

    /**
     * Date fields to be converted to carbon objects
     * @var bool
     */
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    /* Relationships */

}

app/Http/Controllers/Backend/TransmissionsController.php
<?php namespace App\Http\Controllers\Backend;

use App\Http\Requests\TransmissionRequest;
use App\Dealer\Repositories\Contracts\TransmissionInterface;
use Illuminate\Support\Facades\Request;

class TransmissionsController extends AdminController {

    /**
     * @var
     */
    protected $transmissionRepository;


    public function __construct(TransmissionInterface $transmissionRepository){
        $this->transmissionRepository = $transmissionRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $transmissions = $this->transmissionRepository->sortBy('transmission_name', 'asc')->getAll();
        $data =  $this->respondWithPagination($transmissions,[
            'transmissions' => $transmissions->all()
        ]);
        if(Request::ajax()){
            $view = view('transmissions.partials._transmissions', compact('data'))->render();
            $paginator = str_replace('/?', '?', $data['paginator']['links']);
            return \Response::json(['success'=> true, 'html' => $view, 'paginator'=>$paginator], 200);
        }
        return view('transmissions.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('transmissions.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param TransmissionRequest $request
     * @return mixed
     */
    public function store(TransmissionRequest $request)
    {
        if($this->transmissionRepository->create($request->all())){
            \Session::flash('success', 'Success !! Vehicle transmission has been created.');
            return $this->respondWithSuccess('Success !! Vehicle transmission has been created.');
        }
        return $this->respondNotSaved("Unexpected error just happened");
    }

    /**
     * Display the specified resource.
     * @param $uuid
     * @return mixed
     */
    public function show($uuid)
    {
        $transmission = $this->transmissionRepository->getById($uuid);

        if(!$transmission)
        {
            return $this->respondNotFound('Transmission not found.');
        }

        return $this->respond([
            'data' => $this->transmissionTransformer->transform($transmission)
        ]);

    }

    /**
     * Update the specified resource in storage.
     * @param TransmissionRequest $request
     * @param $uuid
     * @return mixed
     */
    public function update(TransmissionRequest $request, $uuid)
    {
        if($this->transmissionRepository->update($request->all(), $uuid)){
            return $this->respondWithSuccess('Success !! Vehicle transmission has been updated.');
        }
        return $this->respondNotSaved("Unexpected error just happened");
    }

    /**
     * Remove the specified resource from storage.
     * @param $uuid
     * @return mixed
     */
    public function destroy($uuid)
    {
        if($uuid == 'delete_multiple'){
            $items = json_decode($_POST['items']);
            foreach($items as $transmission){
                $this->transmissionRepository->delete($transmission);
            }
            \Session::flash('success', 'Success !! Vehicle transmissions have been deleted.');
            return \Response::json(['success'=> true, 'message' => 'Vehicle transmissions deleted successfully'], 200);
        }
        else{
            if($this->transmissionRepository->delete($uuid)){
                \Session::flash('success', 'Success !! Vehicle transmission has been deleted.');
            }else{
                \Session::flash('error', 'Error !! Error deleting Vehicle transmission try again.');
            }
            return redirect('backend/transmissions');
        }
    }
}

app/Http/Controllers/TransmissionsController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\TransmissionRequest;
use App\Dealer\Repositories\Contracts\TransmissionInterface;
use App\Dealer\Transformers\TransmissionTransformer;
use Illuminate\Support\Facades\Request;

class TransmissionsController extends ApiController {

    /**
     * @var
     */
    protected $transmissionRepository;

    /**
     * @var
     */

    protected $transmissionTransformer;

    public function __construct(TransmissionInterface $transmissionRepository, TransmissionTransformer $transmissionTransformer){
        $this->transmissionRepository = $transmissionRepository;
        $this->transmissionTransformer = $transmissionTransformer;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {

        //retrieve current time of server before touching the database.
        $now = time();
        //The timestamp of the last sync call made by client
        // - if not available we assume its the first time the call is made
        //  and therefore provide no data to delete as the client has no data yet

        $modifiedSince = Request::input('modifiedSince', null);
        $syncData = $this->transmissionRepository->getAll();
        //Ids to desync
        $desync = null;

        if(null != $modifiedSince && is_numeric($modifiedSince)){
            //the client has timestamp
            // so return only records that have been touched since then
            $syncData = $this->transmissionRepository->getUpdated($modifiedSince);

            //send a list of ids to desync
            $desync = $this->transmissionRepository->getDeleted($modifiedSince);

        }else{
            return $this->respondWithPagination($syncData, [
                'data' => $this->transmissionTransformer->transformCollection($syncData->all()),
                'timestamp' => $now
            ]);
        }

        //send only the ids for the records to be deleted
        if(isset($desync)){
            $desync = $desync->fetch('uuid')->toArray();
        }

        if(null == $syncData){
            return $this->respondNotFound('No vehicle transmission found');
        }

        return $this->respondWithPagination($syncData, [
            'data' => $this->transmissionTransformer->transformCollection($syncData->all()),
            'timestamp' => $now,
            'desync'    => $desync
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     * @param TransmissionRequest $request
     * @return mixed
     */
    public function store(TransmissionRequest $request)
    {
        if($this->transmissionRepository->create($request->all())){
            return $this->respondWithSuccess('Success !! Vehicle transmission has been created.');
        }
        return $this->respondNotSaved("Unexpected error just happened");
    }

    /**
     * Display the specified resource.
     * @param $uuid
     * @return mixed
     */
    public function show($uuid)
    {
        $transmission = $this->transmissionRepository->getById($uuid);

        if(!$transmission)
        {
            return $this->respondNotFound('Transmission not found.');
        }

        return $this->respond([
            'data' => $this->transmissionTransformer->transform($transmission)
        ]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     * @param TransmissionRequest $request
     * @param $uuid
     * @return mixed
     */
    public function update(TransmissionRequest $request, $uuid)
    {
        if($this->transmissionRepository->update($request->all(), $uuid)){
            return $this->respondWithSuccess('Success !! Vehicle transmission has been updated.');
        }
        return $this->respondNotSaved("Unexpected error just happened");
    }

    /**
     * Remove the specified resource from storage.
     * @param $uuid
     * @return mixed
     */
    public function destroy($uuid)
    {
        if($this->transmissionRepository->delete($uuid)){
            return $this->respondWithSuccess('Success !! Vehicle transmission has been deleted');
        }
        return $this->respondNotFound('Vehicle transmission not deleted');
    }

}

resources/views/transmissions/create.blade.php
@extends('layouts.modal')

@section('content')
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h5>@Lang('app.add_transmission_title')</h5>
        </div>
        {!! Form::open(['route' => ['backend.transmissions.store'], 'class' => 'ajax-submit']) !!}
        <div class="modal-body">
            <div class="form-group">
                {!! Form::label('transmission_name', Lang::get('app.transmission_name')) !!}
                {!! Form::text('transmission_name', null, ['class'=>'form-control required', 'required']) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-success">@Lang('app.save')</button>
            <button type="button" data-dismiss="modal" class="btn btn-danger">@Lang('app.close')</button>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/transmissions/index.blade.php
@extends('layouts.main')

@section('content')
<div class="col-md-12 content-header">
    <div class="col-md-6">
        <h3><i class="fa fa-wrench"></i> @Lang('app.transmissions_title') </h3>
    </div>
    <div class="col-md-6">
        <h3><a class="btn btn-primary pull-right" data-toggle="ajax-modal" href="{{ route('backend.transmissions.create') }}"><i class="fa fa-plus"></i> @Lang('app.add_btn')</a></h3>
    </div>
</div>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">

                @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
                @endif
                @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
                @endif
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">

                        <tr>
                            <th width="5%">Count</th>
                            <th width="10%">
                                <div class="radio">
                                    <label for="select_all"> {!! Form::checkbox('select_all','1',null,['class'=>'minimal', 'id'=>'select_all']) !!} </label> &nbsp;
                                </div>
                            </th>
                            <th width="15%">@Lang('app.transmission_name')</th>
                            <th>@Lang('app.action')</th>
                        </tr>
                        <tbody id="listing_body">
                        <?php $counter = getCounter($data['paginator']); ?>
                        @foreach($data['transmissions'] as $count => $transmission)
                        <tr>
                            <td>{{ $counter }}</td>
                            <td>
                                <div class="radio">
                                    <label for="{{$transmission['uuid']}}"> {!! Form::checkbox('selected',$transmission['uuid'],null,['class'=>'minimal select_record']) !!} </label> &nbsp;
                                </div>
                            </td>
                            <td><a class="xedit" data-field-name="transmission_name" data-url="{{ route('backend.transmissions.update', $transmission->uuid) }}" data-title="Edit transmission Name"> {{ $transmission->transmission_name }} </a></td>
                            <td>
                                {!! Form::open(array("method"=>"DELETE", "route" => ['backend.transmissions.destroy', $transmission['uuid']], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                                    <a class="btn btn-danger btn-sm btn-delete"><i class="fa fa-trash"></i>  @Lang('app.delete')</a>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        <?php $counter++ ?>
                        @endforeach
                        </tbody></table>
                    <div  id="paginationWrapper" style="text-align: center">
                        {!! str_replace('/?', '?', $data['paginator']['links']) !!}
                    </div>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
                    {!! Form::open(array("method"=>"DELETE", "route" => ['backend.transmissions.destroy', ''], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                    <a class="btn btn-danger btn-sm btn-delete-multiple"><i class="fa fa-trash"></i> @Lang('app.delete_multiple') </a>
                    {!! Form::close() !!}

        </div>
    </div>
</section>
@endsection
@section ('js_scripts')
        @include('transmissions.partials._transmissions_js')
@endsection