app/Http/routes.php
<?php

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

#Installation script Routes
Route::group(array('prefix'=>'install','before'=>'install'),function()
{
    Route::get('/','Backend\InstallController@index');
    Route::get('/database','Backend\InstallController@getDatabase');
    Route::post('/database','Backend\InstallController@postDatabase');
    Route::get('/user','Backend\InstallController@getUser');
    Route::post('/user','Backend\InstallController@postUser');
});

//Route::group(['middleware' => 'install'], function(){
Route::group(['middleware' => 'auth'], function(){
    Route::get('/', 'Backend\DashboardController@index');
    Route::get('home', 'Backend\DashboardController@index');
    Route::group(array('prefix'=>'backend', 'middleware' => 'auth' ),function()
    {
        Route::resource('colors', 'Backend\ColorsController');
        Route::resource('categories', 'Backend\CategoriesController');
        Route::resource('conditions', 'Backend\ConditionsController');
        Route::resource('features', 'Backend\FeaturesController');
        Route::resource('fuels', 'Backend\FuelsController');
        Route::resource('makes', 'Backend\MakesController');
        Route::resource('transmissions', 'Backend\TransmissionsController');
        Route::resource('models', 'Backend\VehicleModelsController');
        Route::resource('listings', 'Backend\ListingsController');
        Route::post('listings/getModels', 'Backend\ListingsController@getModels');
        Route::resource('images', 'Backend\ImagesController');
        Route::resource('users', 'Backend\UsersController');
        Route::resource('settings', 'Backend\SettingsController');
        # Profile
        Route::get('profile', 'Backend\UsersController@editProfile');
        Route::post('profile', 'Backend\UsersController@updateProfile');
        #listings
        Route::get('listingsFilter', 'Backend\ListingsController@filter');
        #models
        Route::get('modelsFilter', 'Backend\VehicleModelsController@filter');
    });
});
//});
Route::resource('colors', 'ColorsController');
Route::resource('categories', 'CategoriesController');
Route::resource('conditions', 'ConditionsController');
Route::resource('features', 'FeaturesController');
Route::resource('fuels', 'FuelsController');
Route::resource('makes', 'MakesController');
Route::resource('transmissions', 'TransmissionsController');
Route::resource('models', 'VehicleModelsController');
Route::resource('listings', 'ListingsController');
Route::resource('feature_listings', 'FeatureListingController');
Route::resource('vehicle_images', 'VehicleImagesController');
Route::get('settings', 'SettingsController@index');


//protected routes
Route::group(array('prefix' => 'api/v1', 'before' => 'oauth'), function () {
    Route::resource('colors', 'ColorsController');
});
//Route::resource('colors', 'ColorsController', array('only' => array('index', 'show')));


//Respond to incoming access token requests
Route::post('api/v1/oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});

app/Fuel.php
<?php namespace App;

class Fuel extends BaseModel {

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'fuels';

    /**
     * Main table primary key
     * @var string
     */
    protected $primaryKey = 'uuid';

    /**
     * Entities fields to be mass assigned
     * @var array
     */
    protected $fillable = array('uuid','fuel_name');

    /**
     * Date fields to be converted to carbon objects
     * @var bool
     */
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    /* Relationships */

}

app/Http/Controllers/Backend/FuelsController.php
<?php namespace App\Http\Controllers\Backend;

use App\Http\Requests\FuelRequest;
use App\Dealer\Repositories\Contracts\FuelInterface;
use Illuminate\Support\Facades\Request;

class FuelsController extends AdminController {

    /**
     * @var
     */
    protected $fuelRepository;

    public function __construct(FuelInterface $fuelRepository){
        $this->fuelRepository = $fuelRepository;
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
        $fuels = $this->fuelRepository->sortBy('fuel_name', 'asc')->getAll();
        $data =  $this->respondWithPagination($fuels,[
            'fuels' => $fuels->all()
        ]);
        if(Request::ajax()){
            $view = view('fuels.partials._fuels', compact('data'))->render();
            $paginator = str_replace('/?', '?', $data['paginator']['links']);
            return \Response::json(['success'=> true, 'html' => $view, 'paginator'=>$paginator], 200);
        }
        return view('fuels.index',compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        return view('fuels.create');
	}

    /**
     * Store a newly created resource in storage.
     * @param FuelRequest $request
     * @return mixed
     */
    public function store(FuelRequest $request)
	{
        if($this->fuelRepository->create($request->all())){
            \Session::flash('success', 'Success !! Fuel has been added.');
            return $this->respondWithSuccess('Success !! Fuel has been created.');
        }

        return $this->respondNotSaved("Unexpected error just happened");
	}

    /**
     * Display the specified resource.
     * @param $uuid
     * @return mixed
     */
    public function show($uuid)
	{
        $fuel = $this->fuelRepository->getById($uuid);

        if(!$fuel)
        {
            return $this->respondNotFound('Fuel not found.');
        }

        return $this->respond([
            'data' => $this->fuelTransformer->transform($fuel)
        ]);

	}

    /**
     * Update the specified resource in storage.
     * @param FuelRequest $request
     * @param $uuid
     * @return mixed
     */
    public function update(FuelRequest $request, $uuid)
	{
        if($this->fuelRepository->update($request->all(), $uuid)){
            return $this->respondWithSuccess('Success !! Fuel has been updated.');
        }

        return $this->respondNotSaved("Unexpected error just happened");
	}

    /**
     * Remove the specified resource from storage.
     * @param $uuid
     * @return mixed
     */
    public function destroy($uuid)
	{
        if($uuid == 'delete_multiple'){
            $items = json_decode($_POST['items']);
            foreach($items as $fuel){
                $this->fuelRepository->delete($fuel);
            }
            \Session::flash('success', 'Success !! Fuels have been deleted.');
            return \Response::json(['success'=> true, 'message' => 'Fuels deleted successfully'], 200);
        }
        else{
            if($this->fuelRepository->delete($uuid)){
                \Session::flash('success', 'Success !! Fuel has been deleted.');
            }else{
                \Session::flash('error', 'Error !! Error deleting Fuel try again.');
            }
            return redirect('backend/fuels');
            }
    }

}

app/Http/Controllers/FuelsController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\FuelRequest;
use App\Dealer\Repositories\Contracts\FuelInterface;
use App\Dealer\Transformers\FuelTransformer;
use Illuminate\Support\Facades\Request;

class FuelsController extends ApiController {

    /**
     * @var
     */
    protected $fuelRepository;

    /**
     * @var
     */

    protected $fuelTransformer;

    public function __construct(FuelInterface $fuelRepository, FuelTransformer $fuelTransformer){
        $this->fuelRepository = $fuelRepository;
        $this->fuelTransformer = $fuelTransformer;
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
        //retrieve current time of server before touching the database.
        $now = time();
        //The timestamp of the last sync call made by client
        // - if not available we assume its the first time the call is made
        //  and therefore provide no data to delete as the client has no data yet

        $modifiedSince = Request::input('modifiedSince', null);
        $syncData = $this->fuelRepository->getAll();
        //Ids to desync
        $desync = null;

        if(null != $modifiedSince && is_numeric($modifiedSince)){
            //the client has timestamp
            // so return only records that have been touched since then
            $syncData = $this->fuelRepository->getUpdated($modifiedSince);

            //send a list of ids to desync
            $desync = $this->fuelRepository->getDeleted($modifiedSince);

        }else{
            return $this->respondWithPagination($syncData, [
                'data' => $this->fuelTransformer->transformCollection($syncData->all()),
                'timestamp' => $now
            ]);
        }

        //send only the ids for the records to be deleted
        if(isset($desync)){
            $desync = $desync->fetch('uuid')->toArray();
        }

        if(null == $syncData){
            return $this->respondNotFound('No fuels found');
        }

        return $this->respondWithPagination($syncData, [
            'data' => $this->fuelTransformer->transformCollection($syncData->all()),
            'timestamp' => $now,
            'desync'    => $desync
        ]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}

    /**
     * Store a newly created resource in storage.
     * @param FuelRequest $request
     * @return mixed
     */
    public function store(FuelRequest $request)
	{
        if($this->fuelRepository->create($request->all())){
            return $this->respondWithSuccess('Success !! Fuel has been created.');
        }

        return $this->respondNotSaved("Unexpected error just happened");
	}

    /**
     * Display the specified resource.
     * @param $uuid
     * @return mixed
     */
    public function show($uuid)
	{
        $fuel = $this->fuelRepository->getById($uuid);

        if(!$fuel)
        {
            return $this->respondNotFound('Fuel not found.');
        }

        return $this->respond([
            'data' => $this->fuelTransformer->transform($fuel)
        ]);

	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

    /**
     * Update the specified resource in storage.
     * @param FuelRequest $request
     * @param $uuid
     * @return mixed
     */
    public function update(FuelRequest $request, $uuid)
	{
        if($this->fuelRepository->update($request->all(), $uuid)){
            return $this->respondWithSuccess('Success !! Fuel has been updated.');
        }

        return $this->respondNotSaved("Unexpected error just happened");
	}

    /**
     * Remove the specified resource from storage.
     * @param $uuid
     * @return mixed
     */
    public function destroy($uuid)
	{
        if($this->fuelRepository->delete($uuid)){
            return $this->respondWithSuccess('Success !! Fuel has been deleted');
        }
        return $this->respondNotFound('Fuel not deleted');
	}

}

resources/views/fuels/create.blade.php
@extends('layouts.modal')

@section('content')
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h5>@Lang('app.add_fuel_title')</h5>
        </div>
        {!! Form::open(['route' => ['backend.fuels.store'], 'class' => 'ajax-submit']) !!}
        <div class="modal-body">
            <div class="form-group">
                {!! Form::label('fuel_name', Lang::get('app.fuel_name')) !!}
                {!! Form::text('fuel_name', null, ['class'=>'form-control required', 'required']) !!}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-success">@Lang('app.save')</button>
            <button type="button" data-dismiss="modal" class="btn btn-danger">@Lang('app.close')</button>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/fuels/index.blade.php
@extends('layouts.main')

@section('content')
<div class="col-md-12 content-header">
    <div class="col-md-6">
        <h3><i class="fa fa-fire"></i> @Lang('app.fuels_title') </h3>
    </div>
    <div class="col-md-6">
        <h3><a class="btn btn-primary pull-right" data-toggle="ajax-modal" href="{{ route('backend.fuels.create') }}"><i class="fa fa-plus"></i> @Lang('app.add_btn')</a></h3>
    </div>
</div>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">

                @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
                @endif
                @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
                @endif
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th width="5%">Count</th>
                            <th width="10%">
                                <div class="radio">
                                    <label for="select_all"> {!! Form::checkbox('select_all','1',null,['class'=>'minimal', 'id'=>'select_all']) !!} </label> &nbsp;
                                </div>
                            </th>
                            <th width="15%">@Lang('app.fuel_name')</th>
                            <th>@Lang('app.action')</th>
                        </tr>
                        <tbody id="listing_body">
                        <?php $counter = getCounter($data['paginator']); ?>
                        @foreach($data['fuels'] as $count => $fuel)
                        <tr>
                            <td>{{ $counter }}</td>
                            <td>
                                <div class="radio">
                                    <label for="{{$fuel['uuid']}}"> {!! Form::checkbox('selected',$fuel['uuid'],null,['class'=>'minimal select_record']) !!} </label> &nbsp;
                                </div>
                            </td>
                            <td><a class="xedit" data-field-name="fuel_name" data-url="{{ route('backend.fuels.update', $fuel->uuid) }}" data-title="Edit fuel Name"> {{ $fuel->fuel_name }} </a></td>
                            <td>
                                {!! Form::open(array("method"=>"DELETE", "route" => ['backend.fuels.destroy', $fuel['uuid']], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                                    <a class="btn btn-danger btn-sm btn-delete"><i class="fa fa-trash"></i>  @Lang('app.delete')</a>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        <?php $counter++ ?>
                        @endforeach
                        </tbody></table>
                    <div  id="paginationWrapper" style="text-align: center">
                        {!! str_replace('/?', '?', $data['paginator']['links']) !!}
                    </div>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
                    {!! Form::open(array("method"=>"DELETE", "route" => ['backend.fuels.destroy', ''], 'class' => 'form-inline', 'style'=>'display:inline')) !!}
                    <a class="btn btn-danger btn-sm btn-delete-multiple"><i class="fa fa-trash"></i> @Lang('app.delete_multiple') </a>
                    {!! Form::close() !!}

        </div>
    </div>
</section>
@endsection
@section ('js_scripts')
        @include('fuels.partials._fuels_js')
@endsection